# EmporiUm Business Sales Analysis
## Sale Territories and Manager

- Florida- Lana Llana.
- Maine- Erbayne Middleton.
  
 This project focuses on analyzing business sales data for EmporiUm using Python and Jupyter Notebook. EmporiUm is a growing bookstore company that also sells technology products, art supplies, and other merchandise through both in-store and online sales channels.

 In this project, I will import, clean, and analyze sales data to better understand business performance in my assigned territories. I will examine monthly revenue trends, compare store performance, identify top customers, review product category sales, and create charts using Matplotlib to visualize my findings. Based on the results of my analysis, I will also provide recommendations on where marketing efforts should be focused for the next quarter.

## Importing libraries

In [25]:
# import brings tools into python 
# numpy is used marth operations and working with numbers
# pandas is used for reading and analyzing data tables
# matplotlib is used to create chart and visuals
# %matplotlib inline displays charts inthe notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
%matplotlib inline

### Loading Customer List csv

In [26]:
# loading my csv file usind the pd.read_csv() and
# confirming column namesm, non-null and data type using info()
# pd.read_csv() reads a csv file into python
# df_customers is the variable that stores the customer table

# The customer file uses | as a seperator. so i use , sep='|' to make the data mor readable
# Customer_list csv
df_customers = pd.read_csv('customer_list.csv', sep='|')
df_customers.info()
df_customers.head()

<class 'pandas.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cust_id       521 non-null    int64
 1   date          521 non-null    str
 2   time          521 non-null    str
 3   name          521 non-null    str
 4   email         521 non-null    str
 5   phone         520 non-null    str
 6   sms-opt-out   520 non-null    str
dtypes: int64(1), str(6)
memory usage: 28.6 KB

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N

### Loading Product Categories csv

In [27]:
# Same for ProductCategoris csv

# df_categories stores product category info.
# it help connect product to categories and subcategories.
df_categories = pd.read_csv('ProductCategories.csv')
df_categories.info()
df_categories.head()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     str
 2   SubcategoryID  52 non-null     str
 3   Subcategory    52 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.8 KB

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

### Loading Products csv

In [28]:
# This file will be merged with sales using product Num.
# Product Num is the shared colomn between sales and products
df_products = pd.read_csv('Products.csv')
df_products.info()
df_products.head()

<class 'pandas.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    str
 1   Product        669 non-null    str
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    str
dtypes: int64(1), str(3)
memory usage: 21.0 KB

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

### Loading Store Detail csv

In [29]:
# df_stores keeps store location, state, store id, manager and regiongs.
# this file help to identify florida and Maine store

df_stores = pd.read_csv('storeDetail.csv')
df_stores.info()
df_stores.head()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    str
 1   State              111 non-null    str
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    str
 4   Region             111 non-null    str
 5   Region Director    111 non-null    str
dtypes: int64(1), str(5)
memory usage: 5.3 KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

### Loading Store Sales Dcsv

In [30]:
# df_sales keeps store transaction level sale data.
# this includes informations like; transaction date, store id, rewords id, product number, and sale amount.
# this is the main table used for most of my analysis.
df_sales = pd.read_csv('StoreSales.csv')
df_sales.info()
df_sales.head()

<class 'pandas.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  str
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  str
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), str(2)
memory usage: 12.8 MB

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

# Core Marketing Analysis

## Question 1
Who are the territory managers for the assigned sales territories? What are the store IDs and cities for the stores in each territory?
To answer this question, I first need to identify the stores located in Florida and Maine.
### What I Am Looking For
- Territory manager names  
- Store IDs  
- Store cities and locations  
- Assigned regions for Florida and Maine


### Question 2
What is monthly total revenue for in-store sales in each of the two sales territories over the full period covered by the data?
### logic
To answer this question, I first need to use the merge dataframe in Q1 above so I can identify which transactions belong to Florida and Maine. Next, I will convert the transaction dates into monthly periods and calculate total revenue for each month.

### What I Am Looking For
- What is monthly total revenue for Florida
- over the full period covered by the data?

### Question 3
How would you rank the sales performance of each store in each sales territory? Which are the top-performing stores?

### logc
To answer this question, I will group sales data by store and calculate total revenue for each location. After calculating store revenue totals, I will sort and rank stores from highest to lowest sales to identify the strongest performers within Florida and Maine.

### What I Am Looking For
- Total revenue by store  
- Store rankings  
- Rank 1 stores

### Question 4
Comparing the customer ID from the customer list data with the rewards ID from the sales data, who were the top customers in each sales territory?

### logic
To answer this question, I will connect customer information with sales transactions using RewardsID and customer ID. After matching the records, I will calculate customer spending totals and rank customers by total purchases within Florida and Maine.

### What I Am Looking For
- Customer names and IDs  
- Total customer purchases  
- Customer rankings  
- Highest spending customers in each territory